### ISSUE TITLE
Using DeusExe causes constant stutter, running with original exe - not

### ISSUE THREAD

**Issue by Scr34mik** [mkentie/DeusExe#12]
Hi, it seems on modern systems Deus Exe is having more and more problems. Recently ive discovered that im unable to play with Deus Exe anymore, due to constant stutter. You dont have to go far enough. Just booting a new game and looking around causes stutter. As well as FPS going as low as 40.

My config is : 
Win 10 20H2 - 19042.928
Nvidia Drivers - 466.47
CPU - 8700k
GPU - RTX 2060

The only "solution" i could find is to roll back to original Steam's exe file and play game as normal. Ive tried multiple renderers, changing input and audio settings, as well as setting FPS to 0 and 120. these didnt work. Ive also tried "disable fullscreen optimizations" and setting DPI level to "Application" in application's properties.

**Comment by mkentie** [comment]
Hi,

I've only heard about stutters when running recent nvidia drivers with the d3d10 renderer, though the fact that the original exe runs fine for you suggests it's due to Deus Exe, not the renderer.
Unfortunately Deus Exe + d3d10 renderer runs fine on the systems I've tested with.

-Marijn

**Comment by Scr34mik** [comment]
After thorough testing i came to conclusion that ive submitted wrong data. The issue was with DX10 renderer itself. It just didnt stutter that much while running in original exe.
